title: The Interledger Project
email: info@interledger.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://interledger.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: interledger
github_username:  interledger
interledgerjs_baseurl: https://interledgerjs.github.io/
gems:
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin

# multiple language setting
# https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin
languages: ["en", "ja"]
exclude_from_localizations: ["js", "assets", "css", "presentations"]
  
# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
